version: '3.7'

services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      SQL_HOST: db
      SQL_PORT: 5432

    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_DB: dbname
      POSTGRES_PASSWORD: dbpass

volumes:
  postgres_data:
