version: '3.7'

services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: leasing
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: leasing
      SQL_USER: leasing
      SQL_PASSWORD: leasing
      SQL_HOST: db
      SQL_PORT: 5432
      AUTH_JWT_SECRET: secret
      EFK_HOST: ""
      EFK_PORT: 8080

    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: leasing
      POSTGRES_DB: leasing
      POSTGRES_PASSWORD: leasing

volumes:
  postgres_data:
